# Generated by Django 3.2.7 on 2023-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_rto', '0002_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
