# Generated by Django 3.2.7 on 2023-06-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_rto', '0003_checkpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('ownwer_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('cmpny_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('engine_cc', models.CharField(max_length=100)),
                ('ins_exdate', models.CharField(max_length=100)),
                ('pollution_edate', models.CharField(max_length=100)),
                ('reg_edate', models.CharField(max_length=100)),
                ('ins', models.FileField(upload_to='')),
                ('pollution', models.FileField(upload_to='')),
            ],
        ),
    ]
