# Generated by Django 3.2.7 on 2023-06-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_rto', '0004_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('checkpost_id', models.CharField(max_length=100)),
            ],
        ),
    ]
