# Generated by Django 3.2.7 on 2023-06-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_rto', '0005_fines'),
    ]

    operations = [
        migrations.CreateModel(
            name='fines_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('card_name', models.CharField(max_length=100)),
                ('card_no', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
            ],
        ),
    ]
